### ISSUE TITLE
[question] Convert Markdown to HTML

### ISSUE THREAD

**Issue by libra189** [i-tanaka730/qiita_backupper#2]
Hello
Thank you for posting to [Qiita](https://qiita.com/i-tanaka730/items/6ba423abbcddde62c187).
I have a question.
Are you planning to implement a function for convert Markdown to HTML.

I'm sorry for my bad English
Have a good day.

**Comment by i-tanaka730** [comment]
Thank you for your comment, very happy!!
I'm sorry for the late reply...
I modified it so that I can output it in HTML format.
But, it is a simple one using github api.
I'm sorry if it is not a satisfying result.
